apiVersion: v1
kind: Pod
metadata:
  name: "fio-{{ .Values.rtc }}-emptydir-disk"
  namespace: io-test
spec:
  runtimeClassName: "kata-{{ .Values.rtc }}"
  containers:
  - command:
    - kube-apiserver
    - --feature-gates=PodOverhead=false
  - name: fio
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    resources:
      requests:
        cpu: "{{ .Values.resources.requests.cpu }}"
      limits:
        cpu: "{{ .Values.resources.limits.cpu }}"
    volumeMounts:
    - mountPath: /test-volume
      name: emptydir-volume
  volumes:
  - name: emptydir-volume
    emptyDir: {}
