apiVersion: apps/v1
kind: Deployment
metadata:
  name: fio-qemu-emptydir-memory
spec:
  selector:
    matchLabels:
      app: fio-qemu-emptydir-memory
  replicas: 1
  template:
    metadata:
      labels:
        app: fio-qemu-emptydir-memory
    spec:
      runtimeClassName: kata-qemu
      containers:
      - name: fio
        image: mauke53/fio:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /test-volume
          name: emptydir-volume
      volumes:
        - name: emptydir-volume
          emptyDir:
            medium: Memory
            sizeLimit: "8Gi"
