apiVersion: apps/v1
kind: Deployment
metadata:
  name: fio-clh-emptydir-disk
spec:
  selector:
    matchLabels:
      app: fio-clh-emptydir-disk
  replicas: 1
  template:
    metadata:
      labels:
        app: fio-clh-emptydir-disk
    spec:
      runtimeClassName: kata-clh
      containers:
      - name: fio
        image: mauke53/fio:latest
        resources:
          requests:
            cpu: "2"
          limits:
            cpu: "2"
        volumeMounts:
        - mountPath: /test-volume
          name: emptydir-volume
        - mountPath: /results
          name: result-volume
      volumes:
        - name: emptydir-volume
          emptyDir: {}
        - name: result-volume
          hostPath:
            path: /results
