apiVersion: apps/v1
kind: Deployment
metadata:
  name: fio-qemu-virtiofs-emptydir
spec:
  selector:
    matchLabels:
      app: fio-qemu-virtiofs-emptydir
  replicas: 1
  template:
    metadata:
      labels:
        app: fio
    spec:
      runtimeClassName: kata-qemu-virtiofs
      containers:
      - name: fio
        image: mauke53/fio:latest
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /emptydir
          name: emptydir-volume
      volumes:
        - name: emptydir-volume
          emptyDir:
            medium: Memory
            sizeLimit: "4Gi"
