apiVersion: apps/v1
kind: Deployment
metadata:
  name: fio-clh-pv
spec:
  selector:
    matchLabels:
      app: fio-clh-pv
  replicas: 1
  template:
    metadata:
      labels:
        app: fio-clh-pv
    spec:
      runtimeClassName: kata-clh
      containers:
      - name: fio
        image: mauke53/fio:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /test-volume
          name: pv-local
      volumes:
      - name: pv-local
        persistentVolumeClaim:
          claimName: pvc-local
