apiVersion: v1
kind: Pod
metadata:
  name: "fio-{{ .Values.rtc }}-hostpath"
  namespace: io-test
spec:
  runtimeClassName: "kata-{{ .Values.rtc }}"
  containers:
    - name: fio
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      resources:
        requests:
          cpu: "{{ .Values.resources.requests.cpu }}"
        limits:
          cpu: "{{ .Values.resources.limits.cpu }}"
      volumeMounts:
      - mountPath: /test-volume
        name: hostpath-volume
  volumes:
  - name: hostpath-volume
    hostPath:
      path: /test-volume
      type: FileOrCreate