apiVersion: v1
kind: Pod
metadata:
  name: "fio-{{ .Values.rtc }}-pv"
  namespace: io-test
spec:
  runtimeClassName: "kata-{{ .Values.rtc }}"
  containers:
  - name: fio
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    resources:
      requests:
        cpu: "{{ .Values.resources.requests.cpu }}"
        memory: "{{ .Values.resources.requests.memory }}"
      limits:
        cpu: "{{ .Values.resources.limits.cpu }}"
        memory: "{{ .Values.resources.limits.memory }}"
    volumeMounts:
    - mountPath: /test-volume
      name: pv-local
  volumes:
  - name: pv-local
    persistentVolumeClaim:
      claimName: pvc-local
